export const blog = {
  hero: {
    eyebrow: "[ THE BLOG ]",
    title: "Learn AI for Free",
    subtitle:
      "Explore our free learning tracks covering prompt engineering, AI tools, creative AI, vibe coding, and more.",
    stats: [
      { value: "100", label: "Articles" },
      { value: "6", label: "Learning Tracks" },
    ],
  },
  categories: [
    {
      slug: "prompt-engineering",
      name: "Prompt Engineering",
      count: 16,
      description:
        "Master the art of communicating with AI. Learn techniques like chain-of-thought, few-shot prompting and more.",
    },
    {
      slug: "ai-tools",
      name: "AI Tools & Models",
      count: 18,
      description:
        "Compare and master the leading AI models — ChatGPT, Claude, Gemini, and more.",
    },
    {
      slug: "ai-art",
      name: "AI Art & Creative",
      count: 14,
      description:
        "Create stunning visuals with MidJourney, DALL-E, and Stable Diffusion.",
    },
    {
      slug: "vibe-coding",
      name: "Vibe Coding",
      count: 12,
      description: "Build apps, websites, and tools without traditional coding.",
    },
    {
      slug: "ai-business",
      name: "AI Business & Productivity",
      count: 22,
      description:
        "Leverage AI to automate workflows, boost productivity, and build AI-powered businesses.",
    },
    {
      slug: "ai-career",
      name: "AI Career & Learning",
      count: 18,
      description:
        "Future-proof your career with AI skills. Explore side hustles, learning paths and more.",
    },
  ],
  posts: [
    { title: "How to Use AI to Learn a New Language Faster", date: "Oct 20", category: "AI Career & Learning", slug: "use-ai-learn-new-language-faster" },
    { title: "AI Tools for Academic Research and Citations", date: "Oct 18", category: "AI Career & Learning", slug: "ai-tools-academic-research-citations" },
    { title: "How to Use ChatGPT to Write Better Essays (Ethically)", date: "Oct 15", category: "AI Career & Learning", slug: "use-chatgpt-write-better-essays" },
    { title: "Best AI Study Tools for College Students in 2025", date: "Oct 12", category: "AI Career & Learning", slug: "best-ai-study-tools-college-students" },
    { title: "How to Use AI Tools as a Student Without Cheating", date: "Oct 10", category: "AI Career & Learning", slug: "use-ai-tools-student-without-cheating" },
    { title: "Make Money with ChatGPT: 10 Real Ways That Work", date: "Oct 8", category: "AI Career & Learning", slug: "make-money-chatgpt-real-ways" },
    { title: "AI Passive Income Ideas: Make Money While You Sleep", date: "Oct 5", category: "AI Career & Learning", slug: "ai-passive-income-ideas" },
    { title: "How to Start an AI Automation Agency (Step-by-Step)", date: "Oct 3", category: "AI Career & Learning", slug: "start-ai-automation-agency-guide" },
    { title: "How to Start a Freelance Business Using Only AI Tools", date: "Oct 1", category: "AI Career & Learning", slug: "start-freelance-business-ai-tools" },
    { title: "AI Side Hustles You Can Start Today with No Experience", date: "Sep 28", category: "AI Career & Learning", slug: "ai-side-hustles-no-experience" },
    { title: "How to Make Money with AI in 2025: 15 Proven Methods", date: "Sep 25", category: "AI Career & Learning", slug: "make-money-with-ai-proven-methods" },
    { title: "AI Agents vs Chatbots: What's the Difference?", date: "Sep 22", category: "AI Career & Learning", slug: "ai-agents-vs-chatbots-difference" },
    { title: "How to Build Your First AI Agent (No Coding Required)", date: "Sep 20", category: "AI Career & Learning", slug: "build-first-ai-agent-no-coding" },
    { title: "What Are AI Agents? A Beginner's Guide to the Future of AI", date: "Sep 18", category: "AI Career & Learning", slug: "what-are-ai-agents-beginners-guide" },
    { title: "AI Skills to Learn in 2025 for Career Growth", date: "Sep 15", category: "AI Career & Learning", slug: "ai-skills-career-growth-2025" },
    { title: "How to Learn AI Without a Technical Background", date: "Sep 12", category: "AI Career & Learning", slug: "learn-ai-without-technical-background" },
    { title: "Is Prompt Engineering a Real Career? Salary & Outlook", date: "Sep 10", category: "AI Career & Learning", slug: "prompt-engineering-career-salary-outlook" },
    { title: "How to Price AI-Powered Freelance Services", date: "Sep 8", category: "AI Business & Productivity", slug: "price-ai-powered-freelance-services" },
    { title: "How to Use AI for Freelance Writing (Earn More, Work Less)", date: "Sep 5", category: "AI Business & Productivity", slug: "ai-freelance-writing-earn-more" },
    { title: "Best AI Tools for Upwork and Fiverr Freelancers", date: "Sep 2", category: "AI Business & Productivity", slug: "best-ai-tools-upwork-fiverr" },
    { title: "How to Use AI to Get More Freelance Clients", date: "Aug 30", category: "AI Business & Productivity", slug: "use-ai-get-more-freelance-clients" },
    { title: "AI Tools Every Freelancer Should Use in 2025", date: "Aug 28", category: "AI Business & Productivity", slug: "ai-tools-every-freelancer-2025" },
    { title: "AI Productivity Stack: The 7 Tools That Replace 20 Apps", date: "Aug 25", category: "AI Business & Productivity", slug: "ai-productivity-stack-replace-apps" },
    { title: "How to Use AI for Data Analysis Without Coding", date: "Aug 22", category: "AI Business & Productivity", slug: "use-ai-data-analysis-without-coding" },
    { title: "AI Tools for Presentations: Create Slide Decks in Minutes", date: "Aug 20", category: "AI Business & Productivity", slug: "ai-tools-presentations-slide-decks" },
    { title: "How to Use AI to Write Reports and Documents Faster", date: "Aug 18", category: "AI Business & Productivity", slug: "use-ai-write-reports-faster" },
    { title: "AI Tools to Save 10 Hours a Week at Work", date: "Aug 15", category: "AI Business & Productivity", slug: "ai-tools-save-10-hours-week" },
    { title: "How to Use AI to Be More Productive at Work", date: "Aug 12", category: "AI Business & Productivity", slug: "use-ai-more-productive-work" },
    { title: "AI for E-commerce: Tools to Boost Sales and Save Time", date: "Aug 10", category: "AI Business & Productivity", slug: "ai-ecommerce-tools-boost-sales" },
    { title: "How to Use AI for Social Media Marketing (Complete Guide)", date: "Aug 8", category: "AI Business & Productivity", slug: "ai-social-media-marketing-guide" },
    { title: "AI Business Plan Generator: Create a Business Plan in 1 Hour", date: "Aug 5", category: "AI Business & Productivity", slug: "ai-business-plan-generator-guide" },
    { title: "How to Use AI for Market Research (Free Methods)", date: "Aug 2", category: "AI Business & Productivity", slug: "use-ai-market-research-free" },
    { title: "Best AI Tools for Small Business Owners in 2025", date: "Jul 30", category: "AI Business & Productivity", slug: "best-ai-tools-small-business-owners" },
    { title: "How to Create AI Workflows That Run on Autopilot", date: "Jul 28", category: "AI Business & Productivity", slug: "create-ai-workflows-autopilot" },
    { title: "AI Customer Service Automation for Small Business", date: "Jul 25", category: "AI Business & Productivity", slug: "ai-customer-service-automation-small-business" },
    { title: "How to Use AI for Meeting Notes and Summaries", date: "Jul 22", category: "AI Business & Productivity", slug: "ai-meeting-notes-summaries" },
    { title: "AI Tools for Email Automation: Write and Send Faster", date: "Jul 20", category: "AI Business & Productivity", slug: "ai-tools-email-automation" },
    { title: "How to Use Zapier AI to Automate Your Workflow", date: "Jul 18", category: "AI Business & Productivity", slug: "zapier-ai-automate-workflow" },
    { title: "How to Automate Repetitive Tasks with AI", date: "Jul 15", category: "AI Business & Productivity", slug: "automate-repetitive-tasks-ai" },
    { title: "How to Use Bolt, Lovable, and Replit AI to Ship Fast", date: "Jul 12", category: "Vibe Coding", slug: "bolt-lovable-replit-ai-ship-products" },
    { title: "Best No-Code AI Tools for Building Projects in 2025", date: "Jul 10", category: "Vibe Coding", slug: "best-no-code-ai-tools-building-projects" },
    { title: "GitHub Copilot vs Cursor AI: Which Code Editor is Best?", date: "Jul 8", category: "Vibe Coding", slug: "github-copilot-vs-cursor-ai-comparison" },
    { title: "How to Automate Tasks with Python and AI", date: "Jul 5", category: "Vibe Coding", slug: "automate-tasks-python-ai-beginner" },
    { title: "Create a Landing Page with AI: Step-by-Step Tutorial", date: "Jul 3", category: "Vibe Coding", slug: "create-landing-page-with-ai" },
    { title: "How to Build an AI Chatbot for Your Business (No Code)", date: "Jul 1", category: "Vibe Coding", slug: "build-ai-chatbot-business-no-code" },
    { title: "Build a Personal Portfolio Website with AI in 1 Hour", date: "Jun 28", category: "Vibe Coding", slug: "build-portfolio-website-ai-one-hour" },
    { title: "How to Use AI to Learn Programming from Scratch", date: "Jun 25", category: "Vibe Coding", slug: "use-ai-learn-programming-scratch" },
    { title: "AI Coding Tools for Absolute Beginners: Where to Start", date: "Jun 22", category: "Vibe Coding", slug: "ai-coding-tools-absolute-beginners" },
    { title: "How to Build an App with AI: No Coding Experience Needed", date: "Jun 20", category: "Vibe Coding", slug: "build-app-with-ai-no-coding" },
    { title: "How to Build a Website Using AI Without Coding", date: "Jun 18", category: "Vibe Coding", slug: "build-website-using-ai-without-coding" },
    { title: "How to Create a Faceless YouTube Channel with AI", date: "Jun 15", category: "AI Art & Creative", slug: "faceless-youtube-channel-ai" },
    { title: "How to Create AI Voiceovers and Podcasts for Free", date: "Jun 12", category: "AI Art & Creative", slug: "create-ai-voiceovers-podcasts" },
    { title: "AI Tools for YouTube: Create Videos 10x Faster", date: "Jun 10", category: "AI Art & Creative", slug: "ai-tools-youtube-creators" },
    { title: "How to Create AI Videos for Beginners", date: "Jun 8", category: "AI Art & Creative", slug: "how-to-create-ai-videos-beginners" },
    { title: "How to Create and Sell Digital Products Using AI", date: "Jun 5", category: "AI Art & Creative", slug: "create-sell-digital-products-ai" },
    { title: "AI Print-on-Demand Business: Start With Zero Investment", date: "Jun 2", category: "AI Art & Creative", slug: "ai-print-on-demand-business-guide" },
    { title: "How to Sell AI Art on Etsy: Complete Side Hustle Guide", date: "May 30", category: "AI Art & Creative", slug: "sell-ai-art-etsy-guide" },
    { title: "AI Tools for Creating Social Media Graphics", date: "May 28", category: "AI Art & Creative", slug: "ai-tools-social-media-graphics" },
    { title: "How to Create AI-Generated Logos for Your Business", date: "May 25", category: "AI Art & Creative", slug: "create-ai-generated-logos" },
    { title: "AI Art for Beginners: Create Stunning Images in Minutes", date: "May 22", category: "AI Art & Creative", slug: "ai-art-beginners-tutorial" },
    { title: "How to Use DALL-E to Create AI Images (Free Guide)", date: "May 20", category: "AI Art & Creative", slug: "how-to-use-dalle-create-ai-images" },
    { title: "How to Write MidJourney Prompts That Look Professional", date: "May 18", category: "AI Art & Creative", slug: "midjourney-prompts-professional-guide" },
    { title: "How to Use MidJourney for Beginners: Step-by-Step", date: "May 15", category: "AI Art & Creative", slug: "how-to-use-midjourney-beginners-tutorial" },
    { title: "Free AI Tools for Graphic Design", date: "May 12", category: "AI Tools & Models", slug: "free-ai-tools-graphic-design" },
    { title: "Best Free AI Chatbots: ChatGPT Alternatives", date: "May 10", category: "AI Tools & Models", slug: "best-free-ai-chatbots-alternatives" },
    { title: "Free AI Tools for Small Business Owners", date: "May 8", category: "AI Tools & Models", slug: "free-ai-tools-small-business" },
    { title: "10 Free AI Tools for Students in 2025", date: "May 5", category: "AI Tools & Models", slug: "free-ai-tools-students" },
    { title: "Best Free AI Tools for Writing in 2025", date: "May 3", category: "AI Tools & Models", slug: "best-free-ai-tools-writing" },
    { title: "20 Best Free AI Tools You Can Start Using Today", date: "May 1", category: "AI Tools & Models", slug: "best-free-ai-tools-no-signup" },
    { title: "How to Use ChatGPT Custom Instructions (Game Changer)", date: "Apr 28", category: "AI Tools & Models", slug: null },
    { title: "How to Use Grammarly AI for Better Writing", date: "Apr 25", category: "AI Tools & Models", slug: "how-to-use-grammarly-ai-writing" },
    { title: "How to Use Canva AI Magic Studio: Complete Design Guide", date: "Apr 22", category: "AI Tools & Models", slug: "how-to-use-canva-ai-magic-studio" },
    { title: "How to Use Notion AI to 10x Your Productivity", date: "Apr 20", category: "AI Tools & Models", slug: "how-to-use-notion-ai-productivity" },
    { title: "How to Use Perplexity AI for Research", date: "Apr 18", category: "AI Tools & Models", slug: "how-to-use-perplexity-ai-research" },
    { title: "How to Use Google Gemini AI: Complete Guide", date: "Apr 15", category: "AI Tools & Models", slug: "how-to-use-google-gemini-ai-guide" },
    { title: "How to Use Claude AI: Beginner's Step-by-Step Tutorial", date: "Apr 12", category: "AI Tools & Models", slug: "how-to-use-claude-ai-beginners-tutorial" },
    { title: "How to Use ChatGPT: Complete Beginner's Guide", date: "Apr 10", category: "AI Tools & Models", slug: "how-to-use-chatgpt-beginners-guide" },
    { title: "ChatGPT Free vs Plus vs Pro: Which Plan is Worth It?", date: "Apr 8", category: "AI Tools & Models", slug: null },
    { title: "Best Free AI Image Generators Compared", date: "Apr 5", category: "AI Tools & Models", slug: "best-free-ai-image-generators-compared" },
    { title: "Best AI Writing Tools Compared", date: "Apr 2", category: "AI Tools & Models", slug: "best-ai-writing-tools-compared" },
    { title: "ChatGPT Prompts for Content Creators: The Ultimate Collection", date: "Mar 30", category: "Prompt Engineering", slug: null },
    { title: "30 ChatGPT Prompts for Brainstorming Business Ideas", date: "Mar 28", category: "Prompt Engineering", slug: null },
    { title: "ChatGPT Prompts for Resume Writing and Job Applications", date: "Mar 25", category: "Prompt Engineering", slug: null },
    { title: "Best ChatGPT Prompts for Social Media Content Creation", date: "Mar 22", category: "Prompt Engineering", slug: null },
    { title: "50 ChatGPT Prompts for Email Writing That Save Hours", date: "Mar 20", category: "Prompt Engineering", slug: null },
    { title: "Prompt Engineering vs Traditional Coding: What's Different?", date: "Mar 18", category: "Prompt Engineering", slug: "prompt-engineering-vs-coding" },
    { title: "How to Get AI to Follow Instructions Perfectly", date: "Mar 15", category: "Prompt Engineering", slug: "get-ai-follow-instructions-perfectly" },
    { title: "Temperature, Top-P, and AI Settings Explained Simply", date: "Mar 12", category: "Prompt Engineering", slug: "ai-temperature-top-p-settings-explained" },
    { title: "How to Use Prompt Chaining for Complex Tasks", date: "Mar 10", category: "Prompt Engineering", slug: "prompt-chaining-complex-tasks" },
    { title: "System Prompts Explained: Control AI Behavior Like a Pro", date: "Mar 8", category: "Prompt Engineering", slug: "system-prompts-explained-guide" },
    { title: "10 Prompt Engineering Mistakes Beginners Make", date: "Mar 5", category: "Prompt Engineering", slug: "prompt-engineering-mistakes-beginners" },
    { title: "Role Prompting: How to Make AI Act Like Any Expert", date: "Mar 2", category: "Prompt Engineering", slug: "role-prompting-technique-guide" },
    { title: "Chain of Thought Prompting: Get Smarter AI Responses", date: "Feb 28", category: "Prompt Engineering", slug: null },
    { title: "Zero-Shot vs Few-Shot Prompting: Which to Use?", date: "Feb 25", category: "Prompt Engineering", slug: "zero-shot-vs-few-shot-prompting-explained" },
    { title: "How to Write Better ChatGPT Prompts: 15 Techniques", date: "Feb 22", category: "Prompt Engineering", slug: "how-to-write-better-chatgpt-prompts" },
    { title: "What is Prompt Engineering? The Complete Guide for 2025", date: "Feb 20", category: "Prompt Engineering", slug: "what-is-prompt-engineering-complete-guide" },
    { title: "ChatGPT vs Claude vs Gemini: Which AI is Best?", date: "Feb 18", category: "AI Tools & Models", slug: null },
    { title: "How to Make Money with AI Art Using MidJourney", date: "Feb 15", category: "AI Art & Creative", slug: "make-money-with-ai-art-midjourney" },
    { title: "Vibe Coding: How to Build Apps Without Code", date: "Feb 12", category: "Vibe Coding", slug: "vibe-coding-build-apps-without-code" },
    { title: "Top 10 AI Skills to Learn in 2025 (With Career Paths)", date: "Feb 10", category: "AI Career & Learning", slug: "top-ai-skills-to-learn-2025" },
  ],
  cta: {
    eyebrow: "WANT THE FULL CURRICULUM?",
    title: "Complete AI Bootcamp",
    body:
      "110+ video lessons, 2,000+ prompts, and 8 comprehensive modules. Taught by Saad A — rated 4.4/5 by 24,318+ students worldwide.",
    perks: [
      "30-Day Money-Back Guarantee",
      "Lifetime Access",
      "Certificate Included",
    ],
    price: 499,
    cta: { label: "Enroll Now — $499", href: "/#pricing" },
  },
};
